// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClientResultController from "./client_result_controller"
application.register("client-result", ClientResultController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import NewClientController from "./new_client_controller"
application.register("new-client", NewClientController)
