services:
  easy_wg_mikrotik:
    restart: unless-stopped
    image: easy_wg_mikrotik
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easy_wg_mikrotik
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      SERVER_ADDRESS: 192.168.88.1
      TZ: "Asia/Seoul"
    volumes:
      - ./.env:/rails/.env
