services:
  easy_wg_mikrotik:
    restart: unless-stopped
    image: easy_wg_mikrotik
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easy_wg_mikrotik
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      MIKROTIK_HOST: 192.168.88.1
      MIKROTIK_PORT: 8728
      # Default locale setting (ko, en, zh, ja)
      DEFAULT_LOCALE: ko
      TZ: "Asia/Seoul"
